' SPDX-FileCopyrightText: 2021 Hyperledger
' SPDX-License-Identifier: CC-BY-4.0

@startuml open_funding_virtual
!pragma teoz true
hide footbox
skinparam SequenceMessageAlign center

participant "Alice\n(Proposer)" as alice
participant "Ingrid\n(Common\nIntermediary)" as ingrid
participant "Bob\n(Proposee)" as bob

alice -> alice: Generate an update on\nparent ledger channel 1\n(between alice &ingrid)\nthat locks the funds\nfor the virtual channel ID\nas per opening balance
&bob -> bob: Generate an update on\nparent ledger channel 2\n(between bob &ingrid)\nthat locks the funds\nfor the virtual channel ID\nas per opening balance

alice -> ingrid: Send the update on the\nparent ledger channel 1
ingrid <- bob: Send the update on the\nparent ledger channel 2

ingrid -[#blue]> ingrid: Accept or\nreject

note over ingrid #LightGray
When rejected, the protocol stops
here and funding will fail
end note

alice <- ingrid: Accept the update on\nparent ledger channel 1
ingrid -> bob: Accept the update on\nparent ledger channel 2


alice -> alice: Virtual channel is funded
&bob -> bob: Virtual channel is funded

legend bottom right
<b>Note:</b>
<color:blue>Blue </color> arrow indicates
user interaction is required.
endlegend

@enduml
