1. SPDX-FileCopyrightText: 2021 Hyperledger
   SPDX-License-Identifier: CC-BY-4.0

@startuml register_generic_progress
hide footbox
skinparam SequenceMessageAlign center

participant "Alice" as alice
participant "Parent Layer" as parentLayer
participant "Bob" as bob


opt if channel has an app
alice -[#blue]> alice: Progress app on-chain\n(next state)
opt if after registering,\nchallenge duration for register has passed \nand that for on-chain progression has not passed
alice -> parentLayer: Progress channel on-chain\n(next state with\nonly actor signature)
opt if on-chain progression using next state\nis allowed by app
parentLayer -> parentLayer: Update registered state\nand\nrestart challenge duration\nfor on-chain progression
alice <- parentLayer: Channel state\nprogressed on-chain
parentLayer -> bob: Channel state\nprogressed on-chain
end
parentLayer -> parentLayer: Wait for challenge duration\nfor on-chain progression\nto expire
parentLayer -> parentLayer: Channel finalized\non-chain 
end
end

legend bottom right
<b>Note:</b>
<color:blue>Blue </color> arrow indicates
user interaction is required.
endlegend

@enduml
