' SPDX-FileCopyrightText: 2021 Hyperledger
' SPDX-License-Identifier: CC-BY-4.0

@startuml register_generic_register
hide footbox
skinparam SequenceMessageAlign center

participant "Alice" as alice
participant "Parent Layer" as parentLayer
participant "Bob" as bob

opt if latest off-chain state is not finalized
alice -> parentLayer: Register state\n(along with signatures\n of all participants)
opt if challenge duration for register has not expired\nand the state is valid
note over parentLayer #LightGray
If a state was already registered, then the
newer state must have a higher version.
end note
parentLayer -> parentLayer:Update registered state\nand\nrestart challenge duration\nfor register
alice <- parentLayer: State registered
parentLayer -> bob: State registered
opt if state registered is not latest
parentLayer <- bob: Register latest state\n(along with signatures\n of all participants)
end
end
parentLayer -> parentLayer: Wait for challenge duration\nfor register to expire
opt if channel has an app
parentLayer -> parentLayer: Start challenge duration\nfor on-chain progression
else if channel does not have an app
parentLayer -> parentLayer: Channel finalized\non-chain 
end
end

@enduml
