@startuml register_generic_register
hide footbox
skinparam SequenceMessageAlign center

participant "Alice" as alice
participant "Parent Layer" as parentLayer
participant "Bob" as bob


opt if latest off-chain state is not finalized
alice -> parentLayer: Register state\n(along with signatures\n of all participants)
parentLayer -> parentLayer: Start challenge duration\nfor register
alice <- parentLayer: State registered
parentLayer -> bob: State registered
opt if state registered is not latest
parentLayer <- bob: Register latest state\n(along with signatures\n of all participants)
opt If bob's state\nis valid\nhas higher version.
parentLayer -> parentLayer: Update registered state\nand restart challenge duration\nfor register
end
end
parentLayer -> parentLayer: Wait for challenge duration\nfor register to expire
opt if channel has an app
parentLayer -> parentLayer: Start challenge duration\nfor on-chain progression
else if channel does not have an app
parentLayer -> parentLayer: Channel finalized\non-chain 
end
end

@enduml
