' SPDX-FileCopyrightText: 2021 Hyperledger
' SPDX-License-Identifier: CC-BY-4.0

@startuml settle_generic_blockchain
hide footbox
skinparam SequenceMessageAlign center

participant "Alice" as alice
participant "Parent Layer" as parentLayer
participant "Bob" as bob

alice -> parentLayer: Conclude
alice <- parentLayer: State concluded
parentLayer -> bob: State concluded

alice -> parentLayer: Withdraw
alice <- parentLayer: Withdrawn for alice

bob -> parentLayer: Withdraw
bob <- parentLayer: Withdrawn for bob

@enduml
